### ISSUE TITLE
Java API

### ISSUE THREAD

**Issue by kopcheski** [Amerousful/gatling-kafka#1]
How does the idea of having a Java API - just like gatling-core have - sound like to you? Is this something you see as added value to this plugin?

**Comment by Amerousful** [comment]
@kopcheski Hey! 
You're just in time! I'm working on that, and I've almost done it. I gonna release it this week.

**Comment by Amerousful** [comment]
The new version with Java support was released. 
`libraryDependencies += "io.github.amerousful" % "gatling-kafka" % "2.0"`
[Here you're an example](https://github.com/Amerousful/gatling-kafka/blob/main/src/test/scala/KafkaJavaExample.java)

I would appreciate any feedback. Feel free to ask questions.

**Comment by kopcheski** [comment]
For my needs, it worked like a charm. Great job!
