### ISSUE TITLE
Добавление trustStorelocation.

### ISSUE THREAD

**Issue by DKanankin** [Amerousful/gatling-kafka#10]
Прошу добавить два параметра 
ssl.truststore.location=/etc/security/tls/kafka.client.truststore.jks
ssl.truststore.password=test1234,
т.к. на текущий момент их использование невозможно.  Спасибо!

**Comment by Amerousful** [comment]
Released in version [3.5](https://github.com/Amerousful/gatling-kafka/releases/tag/3.5) 
```scala
.ssl(
      protocol = "SASL_SSL",
      keystoreLocation = "/var/private/ssl/kafka.keystore.jks",
      keystorePassword = "connector1234",
      keyPassword = "connector1234",
      trustStoreLocation = "/certs/kafka.server.truststore.jks",
      trustStorePassword = "1234"
    )
```
