### ISSUE TITLE
Protobuf Support

### ISSUE THREAD

**Issue by avasilevskii** [Amerousful/gatling-kafka#4]
Currently the plugin supports only plain text/String type for sending/receiving data. 
However, it's quite common for Kafka consumers/producers to use some schema like Avro or Protobuf to encode/decode messages. This is a feature request to add support for Protobuf encoded messages.

**Comment by Amerousful** [comment]
Without doubt, it's a mandatory thing to support different types of data, such as Avro, Protobuf, and Json. I'd be happy to provide this support. 

Yes, I agree that `key` and `value` types have to be generified. I think the most complicated thing will be with the `check` logic. When I implement it, I may come back and share some ideas for advice/consult to hear your thoughts and opinion about it. 

Thanks for your involvement and keen interest!

**Comment by Amerousful** [comment]
@avasilevskii Hey!) 
I've created the [pull request](https://github.com/Amerousful/gatling-kafka/pull/7) for the feature you requested. Could you please take a look? I just want to make sure everything is good and that I've taken into account all the details and nuances.

[Here](https://github.com/Amerousful/gatling-kafka/tree/version_3.0) you can familiarize yourself with the documentation.

**Comment by avasilevskii** [comment]
Wow, that's some really awesome stuff! Many thanks, I will surely take a look and get back to you!

**Comment by Amerousful** [comment]
To be honest, it was a good challenge)

**Comment by avasilevskii** [comment]
Ran through the code and docs: looks just great, didn't find anything to pick on! :D
Looking forward to test it out in the field, thanks again for this great plugin and all the support and development!

**Comment by Amerousful** [comment]
I really appreciate such cool feedback!)

The new version was published and ready to use and test. I am keeping this issue open so we are able to discuss any problems, bugs, etc. in the new version.

**Comment by avasilevskii** [comment]
Hey! I've tried out the plugin today and have a few questions:
1. Should the `schemaUrl` be mandatory when using `io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer`? E.g. in my setup there's no Schema Registry, but rather a client-side library that provides protobuf definitions. As far as I can see, there are also constructors for most classes that do not require a schemaUrl, but somehow they are not used as it seems (didn't dig deep enough yet).
2. As mentioned, I have a Scala library with protobuf classes pre-generated with ScalaPB that are pulled as dependency into the Gatling project. Their content is basically the same as `package proto.service.{AuthLocal, Order, ServiceProto}` in the example you've provided in the documentation. If I try using these with a really simple custom serializer (`producerValueSerializer("com.my.event.protobuf.MyEventSerializer")`), it fails because there are no corresponding generated Java definition classes:
```
java.lang.ClassCastException: class com.my.event.MyEvent$ cannot be cast to class scalapb.JavaProtoSupport (com.my.event.MyEvent$ and scalapb.JavaProtoSupport are in unnamed module of loader 'app')
```
Since the above mentioned shared library is used by many teams and it contains a lot of protobuf definitions that are regularly updated, it's not feasible to copy proto files into the project and regenerate both Scala and Java classes via `protoc-jar-maven-plugin` as proposed in Readme. Would it be possible to remove this tight coupling between the Scala and the Java APIs?
Btw, using a naive Serializer for the sample AuthLocal protobuf definition works fine with the Java class:
```
class AuthLocalSerializer extends Serializer[proto.Service.AuthLocal] {
  override def serialize(topic: String, data: Service.AuthLocal): Array[Byte] = {
    data.toByteArray
  }
}
```

**Comment by Amerousful** [comment]
Yes, schema url is mandatory for `io.confluent.kafka.serializers.protobuf.KafkaProtobufSerializer`, but you can try to disable it with [auto.register.schemas=false](https://docs.confluent.io/platform/current/schema-registry/security/index.html#disabling-auto-schema-registration). 

ScalaPB generates a Scala class that cannot be passed into `KafkaProtobufSerializer`, because it inherits `scalapb.GeneratedMessage`, but for Protobuf it should inherit `com.google.protobuf.Message`
[KafkaProtobufSerializer source code] (https://github.com/confluentinc/schema-registry/blob/master/protobuf-serializer/src/main/java/io/confluent/kafka/serializers/protobuf/KafkaProtobufSerializer.java#L37)
That's why ScalaPB has this option `javaConversions` and methods `toJavaProto` and `fromJavaProto`.

**Comment by Amerousful** [comment]
Actually, there isn't tight coupling between the Scala and the Java. The method `payload` takes `Expression[Any]`. From my part I added only implicit conversion if you pass ScalaPB class.

**Comment by avasilevskii** [comment]
Alright, got it, thanks for the detailed explanation!
So the implicit conversion is the key here... In that case I guess it would be a bit different feature request to allow sending and receiving any data by providing a custom SerDe similarly to the approach described in [this article](https://franklinlindemberg.medium.com/using-protobuf-with-apache-kafka-and-without-schema-registry-8535f43a2569), is that right?

**Comment by Amerousful** [comment]
Implicit conversion **only** for ScalaPB Scala class. As I mentiod above, you can pass in the `payload` whatever you want. 
There isn't any restriction to send as an array of bytes
```scala
.producerValueSerializer("org.apache.kafka.common.serialization.ByteArraySerializer")

.payload { session =>
      val token = session("token").as[String]
      AuthLocal(token, 123, "abc@ex.com").toByteArray
    }
```

**Comment by avasilevskii** [comment]
That's exactly what I needed, thank you again! 😄 
P.S. Maybe it's something worth mentioning in the readme as well.

**Comment by Amerousful** [comment]
You're welcome! 
Yep, it's a good point to update readme and clarify some details with examples.

**Comment by igroeg** [comment]
Hey Folks, as far as I saw, the issue was resolved only for protobuf, but not for avro. Am I correct?
